nodeLinker: node-modules

enableColors: true

enableGlobalCache: false

enableHyperlinks: true

enableProgressBars: true

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"

progressBarStyle: jack

supportedArchitectures:
  os:
    - linux
    - darwin

yarnPath: .yarn/releases/yarn-3.1.1.cjs
